# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBxR7Sfole2UJe8W9_h127-7OiQ0uPRQ
"""

!pip install pandas

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# %matplotlib inline
plt.style.use("ggplot")

import sklearn
from sklearn.decomposition import TruncatedSVD

import io

amazon_ratings = pd.read_csv(io.BytesIO(uploaded['ratings_Beauty.csv']))
amazon_ratings = amazon_ratings.dropna()
amazon_ratings.head()

amazon_ratings.shape

popular_products = pd.DataFrame(amazon_ratings.groupby('ProductId')['Rating'].count())
most_popular = popular_products.sort_values('Rating', ascending=False)
most_popular.head(10)

most_popular.head(30).plot(kind = "bar")